language: cpp

sudo: required
dist: xenial

compiler:
  - clang
  - gcc

before_script:
  - sudo apt update
  - sudo apt install gcc g++ make git
  - sudo apt install libsdl2-dev libglew-dev libglm-dev libassimp-dev
  - cd utils
  - sh install-cmake.sh
  - cd ..
  - mkdir build
  - cd build
  - /usr/local/bin/cmake ..

script: make